name: Add Notice Annotation

on:
  workflow_dispatch:

jobs:
  add_notice_annotation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Notice Annotation
        run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
